-- Database schema for WebTuVanSucKhoe
CREATE DATABASE IF NOT EXISTS tuvansuckhoe;
USE tuvansuckhoe;

CREATE TABLE IF NOT EXISTS tuvan (
    id INT AUTO_INCREMENT PRIMARY KEY,
    HOTEN VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    SDT VARCHAR(20) NOT NULL,
    MOTA TEXT NOT NULL,
    anh VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);